databaseChangeLog = {
  //mysql
  changeSet(author: "marketplace", id: "2.3.1-1", context: "create, 2.3.1", dbms: "mysql") {
	  comment( "DDL statements for creating Marketplace 2.3.1 database structure" )
      preConditions (onFail:"MARK_RAN") {
          not {
              tableExists(tableName:"service_item")
          }
      }
      sql ( """
		create table U_DOMAIN (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, username varchar(255) not null, created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table U_DOMAIN_preferences (preferences bigint, preferences_idx varchar(255), preferences_elt varchar(255) not null) ENGINE=InnoDB;
		create table U_VIEWS (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, isadminview bit not null, created_by_id bigint, name varchar(255) not null, isdefault bit not null, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table avatar (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, is_default bit not null, pic mediumblob, created_by_id bigint, content_type varchar(255), edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table category (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, title varchar(50) not null, description varchar(250), created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table change_detail (id bigint not null auto_increment, version bigint not null, new_value varchar(4000), object_version bigint not null, object_id bigint not null, field_name varchar(255) not null, old_value varchar(4000), object_class_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
		create table change_log (id bigint not null auto_increment, version bigint not null, object_version bigint not null, changed_by_id bigint not null, object_id bigint not null, description varchar(255) not null, object_class_name varchar(255) not null, change_date datetime not null, primary key (id)) ENGINE=InnoDB;
		create table custom_field (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, custom_field_definition_id bigint not null, created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table custom_field_definition (id bigint not null auto_increment, version bigint not null, created_date datetime, tooltip varchar(50), created_by_id bigint, edited_date datetime, edited_by_id bigint, label varchar(50) not null, description varchar(250), is_required bit not null, name varchar(50) not null, style_type varchar(255) not null, primary key (id)) ENGINE=InnoDB;
		create table custom_field_definition_types (cf_definition_types_id bigint, types_id bigint, types_idx integer) ENGINE=InnoDB;
		create table default_images (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, image_id bigint not null, created_by_id bigint, defined_default_type varchar(255) not null, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table drop_down_cf (id bigint not null, value_id bigint, primary key (id)) ENGINE=InnoDB;
		create table drop_down_cfd (id bigint not null, primary key (id)) ENGINE=InnoDB;
		create table ext_profile (id bigint not null, external_view_url varchar(2083), system_uri varchar(255), external_id varchar(255), external_edit_url varchar(2083), primary key (id), unique (system_uri, external_id)) ENGINE=InnoDB;
		create table ext_service_item (id bigint not null, external_view_url varchar(2083), system_uri varchar(255), external_id varchar(255), external_edit_url varchar(2083), primary key (id), unique (system_uri, external_id)) ENGINE=InnoDB;
		create table field_value (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, custom_field_definition_id bigint not null, is_enabled integer not null, display_text varchar(255) not null, created_by_id bigint, edited_date datetime, field_values_idx integer, primary key (id)) ENGINE=InnoDB;
		create table images (id bigint not null auto_increment, version bigint not null, created_date datetime, is_default bit not null, type varchar(255) not null, created_by_id bigint, content_type varchar(255), bytes mediumblob not null, edited_date datetime, edited_by_id bigint, image_size double precision, primary key (id)) ENGINE=InnoDB;
		create table item_comment (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, service_item_id bigint not null, text varchar(250) not null, created_by_id bigint, author_id bigint not null, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table modify_relationship_activity (id bigint not null, primary key (id)) ENGINE=InnoDB;
		create table owf_properties (id bigint not null auto_increment, version bigint not null, visible_in_launch bit not null, edited_by_id bigint, created_date datetime, singleton bit not null, created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table profile (id bigint not null auto_increment, version bigint not null, created_date datetime not null, created_by_id bigint, bio varchar(1000), edited_date datetime, edited_by_id bigint, username varchar(250) not null unique, email varchar(250), avatar_id bigint, display_name varchar(250), primary key (id)) ENGINE=InnoDB;
		create table rating (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, service_item_id bigint not null, created_by_id bigint, author_id bigint not null, rate float not null, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table rejection_activity (id bigint not null, rejection_listing_id bigint, primary key (id)) ENGINE=InnoDB;
		create table rejection_justification (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, title varchar(50) not null, description varchar(250), created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table rejection_listing (id bigint not null auto_increment, version bigint not null, justification_id bigint, edited_by_id bigint, created_date datetime, service_item_id bigint not null, description varchar(2000), created_by_id bigint, author_id bigint not null, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table relationship (id bigint not null auto_increment, version bigint not null, relationship_type varchar(255) not null, owning_entity_id bigint not null, primary key (id)) ENGINE=InnoDB;
		create table relationship_activity_log (mod_rel_activity_id bigint not null, service_item_snapshot_id bigint, items_idx integer) ENGINE=InnoDB;
		create table relationship_service_item (relationship_related_items_id bigint, service_item_id bigint, related_items_idx integer) ENGINE=InnoDB;
		create table service_item (id bigint not null auto_increment, version bigint not null, created_date datetime, owf_properties_id bigint, avg_rate float not null, approval_status varchar(11) not null, title varchar(50) not null, screenshot1url varchar(2083), image_small_url varchar(2083), image_large_url varchar(2083), total_votes integer not null, launch_url varchar(2083), uuid varchar(255) not null, version_name varchar(50) not null, release_date datetime not null, organization varchar(40), dependencies varchar(1000), types_id bigint not null, screenshot2url varchar(2083), created_by_id bigint, requirements varchar(1000), doc_url varchar(2083), tech_poc varchar(255) not null, edited_date datetime, edited_by_id bigint, total_comments integer not null, is_hidden integer not null, description varchar(4000) not null, state_id bigint not null, install_url varchar(2083), last_activity_id bigint, author_id bigint not null, primary key (id)) ENGINE=InnoDB;
		create table service_item_activity (id bigint not null auto_increment, version bigint not null, created_date datetime, action varchar(255) not null, service_item_id bigint not null, service_item_version bigint, created_by_id bigint, edited_date datetime, edited_by_id bigint, activity_timestamp datetime not null, author_id bigint not null, service_item_activities_idx integer, primary key (id)) ENGINE=InnoDB;
		create table service_item_category (service_item_categories_id bigint not null, category_id bigint, categories_idx integer) ENGINE=InnoDB;
		create table service_item_custom_field (service_item_custom_fields_id bigint, custom_field_id bigint, custom_fields_idx integer) ENGINE=InnoDB;
		create table service_item_snapshot (id bigint not null auto_increment, version bigint not null, service_item_id bigint, title varchar(255) not null, primary key (id)) ENGINE=InnoDB;
		create table si_recommended_layouts (service_item_id bigint, recommended_layout varchar(255)) ENGINE=InnoDB;
		create table state (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, is_published bit not null, title varchar(50) not null, description varchar(250), created_by_id bigint, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table text (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, value varchar(250), created_by_id bigint, read_only bit not null, name varchar(50) not null unique, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		create table text_cf (id bigint not null, value varchar(255), primary key (id)) ENGINE=InnoDB;
		create table text_cfd (id bigint not null, primary key (id)) ENGINE=InnoDB;
		create table types (id bigint not null auto_increment, version bigint not null, created_date datetime, title varchar(50) not null, created_by_id bigint, role_access varchar(9) not null, edited_date datetime, edited_by_id bigint, has_launch_url bit not null, is_widget bit not null, description varchar(250), image_id bigint, ozone_aware bit not null, has_icons bit not null, primary key (id)) ENGINE=InnoDB;
		create table user_account (id bigint not null auto_increment, version bigint not null, edited_by_id bigint, created_date datetime, username varchar(250) not null unique, created_by_id bigint, last_login datetime, edited_date datetime, primary key (id)) ENGINE=InnoDB;
		alter table U_DOMAIN add index FK97BAABEE7666C6D2 (created_by_id), add constraint FK97BAABEE7666C6D2 foreign key (created_by_id) references profile (id);
		alter table U_DOMAIN add index FK97BAABEEE31CB353 (edited_by_id), add constraint FK97BAABEEE31CB353 foreign key (edited_by_id) references profile (id);
		alter table U_VIEWS add index FK376C31E47666C6D2 (created_by_id), add constraint FK376C31E47666C6D2 foreign key (created_by_id) references profile (id);
		alter table U_VIEWS add index FK376C31E4E31CB353 (edited_by_id), add constraint FK376C31E4E31CB353 foreign key (edited_by_id) references profile (id);
		alter table avatar add index FKAC32C1597666C6D2 (created_by_id), add constraint FKAC32C1597666C6D2 foreign key (created_by_id) references profile (id);
		alter table avatar add index FKAC32C159E31CB353 (edited_by_id), add constraint FKAC32C159E31CB353 foreign key (edited_by_id) references profile (id);
		alter table category add index FK302BCFE7666C6D2 (created_by_id), add constraint FK302BCFE7666C6D2 foreign key (created_by_id) references profile (id);
		alter table category add index FK302BCFEE31CB353 (edited_by_id), add constraint FK302BCFEE31CB353 foreign key (edited_by_id) references profile (id);
		alter table change_log add index FK80F28E35B624A19E (changed_by_id), add constraint FK80F28E35B624A19E foreign key (changed_by_id) references profile (id);
		alter table custom_field add index FK2ACD76AC7666C6D2 (created_by_id), add constraint FK2ACD76AC7666C6D2 foreign key (created_by_id) references profile (id);
		alter table custom_field add index FK2ACD76ACE31CB353 (edited_by_id), add constraint FK2ACD76ACE31CB353 foreign key (edited_by_id) references profile (id);
		alter table custom_field add index FK2ACD76AC6F62C9ED (custom_field_definition_id), add constraint FK2ACD76AC6F62C9ED foreign key (custom_field_definition_id) references custom_field_definition (id);
		alter table custom_field_definition add index FK150F70C6E31CB353 (edited_by_id), add constraint FK150F70C6E31CB353 foreign key (edited_by_id) references profile (id);
		alter table custom_field_definition add index FK150F70C67666C6D2 (created_by_id), add constraint FK150F70C67666C6D2 foreign key (created_by_id) references profile (id);
		alter table custom_field_definition_types add index FK1A84FFC06928D597 (types_id), add constraint FK1A84FFC06928D597 foreign key (types_id) references types (id);
		alter table default_images add index FK6F064E367666C6D2 (created_by_id), add constraint FK6F064E367666C6D2 foreign key (created_by_id) references profile (id);
		alter table default_images add index FK6F064E36E31CB353 (edited_by_id), add constraint FK6F064E36E31CB353 foreign key (edited_by_id) references profile (id);
		alter table default_images add index FK6F064E36553AF61A (image_id), add constraint FK6F064E36553AF61A foreign key (image_id) references images (id);
		alter table drop_down_cf add index FK13ADE7D0BC98CEE3 (value_id), add constraint FK13ADE7D0BC98CEE3 foreign key (value_id) references field_value (id);
		alter table field_value add index FK29F571EC7666C6D2 (created_by_id), add constraint FK29F571EC7666C6D2 foreign key (created_by_id) references profile (id);
		alter table field_value add index FK29F571ECE31CB353 (edited_by_id), add constraint FK29F571ECE31CB353 foreign key (edited_by_id) references profile (id);
		alter table field_value add index FK29F571ECF1F14D3C (custom_field_definition_id), add constraint FK29F571ECF1F14D3C foreign key (custom_field_definition_id) references drop_down_cfd (id);
		alter table images add index FKB95A8278E31CB353 (edited_by_id), add constraint FKB95A8278E31CB353 foreign key (edited_by_id) references profile (id);
		alter table images add index FKB95A82787666C6D2 (created_by_id), add constraint FKB95A82787666C6D2 foreign key (created_by_id) references profile (id);
		create index itm_cmnt_svc_item_id_idx on item_comment (service_item_id);
		create index itm_cmnt_author_id_idx on item_comment (author_id);
		alter table item_comment add index FKE6D04D337666C6D2 (created_by_id), add constraint FKE6D04D337666C6D2 foreign key (created_by_id) references profile (id);
		alter table item_comment add index FKE6D04D33E31CB353 (edited_by_id), add constraint FKE6D04D33E31CB353 foreign key (edited_by_id) references profile (id);
		alter table item_comment add index FKE6D04D33C7E5C662 (service_item_id), add constraint FKE6D04D33C7E5C662 foreign key (service_item_id) references service_item (id);
		alter table item_comment add index FKE6D04D335A032135 (author_id), add constraint FKE6D04D335A032135 foreign key (author_id) references profile (id);
		alter table owf_properties add index FKE88638947666C6D2 (created_by_id), add constraint FKE88638947666C6D2 foreign key (created_by_id) references profile (id);
		alter table owf_properties add index FKE8863894E31CB353 (edited_by_id), add constraint FKE8863894E31CB353 foreign key (edited_by_id) references profile (id);
		alter table profile add index FKED8E89A9E31CB353 (edited_by_id), add constraint FKED8E89A9E31CB353 foreign key (edited_by_id) references profile (id);
		alter table profile add index FKED8E89A97666C6D2 (created_by_id), add constraint FKED8E89A97666C6D2 foreign key (created_by_id) references profile (id);
		alter table profile add index FKED8E89A961C3343D (avatar_id), add constraint FKED8E89A961C3343D foreign key (avatar_id) references avatar (id);
		create index rating_svc_item_id_idx on rating (service_item_id);
		alter table rating add index FKC815B19D7666C6D2 (created_by_id), add constraint FKC815B19D7666C6D2 foreign key (created_by_id) references profile (id);
		alter table rating add index FKC815B19DE31CB353 (edited_by_id), add constraint FKC815B19DE31CB353 foreign key (edited_by_id) references profile (id);
		alter table rating add index FKC815B19DC7E5C662 (service_item_id), add constraint FKC815B19DC7E5C662 foreign key (service_item_id) references service_item (id);
		alter table rating add index FKC815B19D5A032135 (author_id), add constraint FKC815B19D5A032135 foreign key (author_id) references profile (id);
		alter table rejection_activity add index FKF35C128582548A4A (rejection_listing_id), add constraint FKF35C128582548A4A foreign key (rejection_listing_id) references rejection_listing (id);
		alter table rejection_justification add index FK12B0A53C7666C6D2 (created_by_id), add constraint FK12B0A53C7666C6D2 foreign key (created_by_id) references profile (id);
		alter table rejection_justification add index FK12B0A53CE31CB353 (edited_by_id), add constraint FK12B0A53CE31CB353 foreign key (edited_by_id) references profile (id);
		create index rej_lst_svc_item_id_idx on rejection_listing (service_item_id);
		alter table rejection_listing add index FK3F2BD44E7666C6D2 (created_by_id), add constraint FK3F2BD44E7666C6D2 foreign key (created_by_id) references profile (id);
		alter table rejection_listing add index FK3F2BD44EE31CB353 (edited_by_id), add constraint FK3F2BD44EE31CB353 foreign key (edited_by_id) references profile (id);
		alter table rejection_listing add index FK3F2BD44EC7E5C662 (service_item_id), add constraint FK3F2BD44EC7E5C662 foreign key (service_item_id) references service_item (id);
		alter table rejection_listing add index FK3F2BD44E5A032135 (author_id), add constraint FK3F2BD44E5A032135 foreign key (author_id) references profile (id);
		alter table rejection_listing add index FK3F2BD44E19CEB614 (justification_id), add constraint FK3F2BD44E19CEB614 foreign key (justification_id) references rejection_justification (id);
		alter table relationship add index FKF06476389D70DD39 (owning_entity_id), add constraint FKF06476389D70DD39 foreign key (owning_entity_id) references service_item (id);
		alter table relationship_activity_log add index FK594974BB25A20F9D (service_item_snapshot_id), add constraint FK594974BB25A20F9D foreign key (service_item_snapshot_id) references service_item_snapshot (id);
		alter table relationship_service_item add index FKDA02504C7E5C662 (service_item_id), add constraint FKDA02504C7E5C662 foreign key (service_item_id) references service_item (id);
		create index svc_item_author_id_idx on service_item (author_id);
		alter table service_item add index FK1571565D2746B676 (last_activity_id), add constraint FK1571565D2746B676 foreign key (last_activity_id) references service_item_activity (id);
		alter table service_item add index FK1571565D904D6974 (owf_properties_id), add constraint FK1571565D904D6974 foreign key (owf_properties_id) references owf_properties (id);
		alter table service_item add index FK1571565DE31CB353 (edited_by_id), add constraint FK1571565DE31CB353 foreign key (edited_by_id) references profile (id);
		alter table service_item add index FK1571565D7666C6D2 (created_by_id), add constraint FK1571565D7666C6D2 foreign key (created_by_id) references profile (id);
		alter table service_item add index FK1571565D6928D597 (types_id), add constraint FK1571565D6928D597 foreign key (types_id) references types (id);
		alter table service_item add index FK1571565D5A032135 (author_id), add constraint FK1571565D5A032135 foreign key (author_id) references profile (id);
		alter table service_item add index FK1571565DDFEC3E97 (state_id), add constraint FK1571565DDFEC3E97 foreign key (state_id) references state (id);
		create index svc_item_act_svc_item_id_idx on service_item_activity (service_item_id);
		alter table service_item_activity add index FK870EA6B1E31CB353 (edited_by_id), add constraint FK870EA6B1E31CB353 foreign key (edited_by_id) references profile (id);
		alter table service_item_activity add index FK870EA6B17666C6D2 (created_by_id), add constraint FK870EA6B17666C6D2 foreign key (created_by_id) references profile (id);
		alter table service_item_activity add index FK870EA6B1C7E5C662 (service_item_id), add constraint FK870EA6B1C7E5C662 foreign key (service_item_id) references service_item (id);
		alter table service_item_activity add index FK870EA6B15A032135 (author_id), add constraint FK870EA6B15A032135 foreign key (author_id) references profile (id);
		create index svc_item_cat_id_idx on service_item_category (service_item_categories_id);
		alter table service_item_category add index FKECC570A0DA41995D (category_id), add constraint FKECC570A0DA41995D foreign key (category_id) references category (id);
		create index svc_item_cst_fld_id_idx on service_item_custom_field (service_item_custom_fields_id);
		alter table service_item_custom_field add index FK46E9894E7B56E054 (custom_field_id), add constraint FK46E9894E7B56E054 foreign key (custom_field_id) references custom_field (id);
		alter table service_item_snapshot add index FKFABD8966C7E5C662 (service_item_id), add constraint FKFABD8966C7E5C662 foreign key (service_item_id) references service_item (id);
		alter table si_recommended_layouts add index FK863C793CC7E5C662 (service_item_id), add constraint FK863C793CC7E5C662 foreign key (service_item_id) references service_item (id);
		alter table state add index FK68AC4917666C6D2 (created_by_id), add constraint FK68AC4917666C6D2 foreign key (created_by_id) references profile (id);
		alter table state add index FK68AC491E31CB353 (edited_by_id), add constraint FK68AC491E31CB353 foreign key (edited_by_id) references profile (id);
		alter table text add index FK36452D7666C6D2 (created_by_id), add constraint FK36452D7666C6D2 foreign key (created_by_id) references profile (id);
		alter table text add index FK36452DE31CB353 (edited_by_id), add constraint FK36452DE31CB353 foreign key (edited_by_id) references profile (id);
		alter table types add index FK69B5879E31CB353 (edited_by_id), add constraint FK69B5879E31CB353 foreign key (edited_by_id) references profile (id);
		alter table types add index FK69B58797666C6D2 (created_by_id), add constraint FK69B58797666C6D2 foreign key (created_by_id) references profile (id);
		alter table types add index FK69B5879553AF61A (image_id), add constraint FK69B5879553AF61A foreign key (image_id) references images (id);
		alter table user_account add index FK14C321B97666C6D2 (created_by_id), add constraint FK14C321B97666C6D2 foreign key (created_by_id) references profile (id);
		alter table user_account add index FK14C321B9E31CB353 (edited_by_id), add constraint FK14C321B9E31CB353 foreign key (edited_by_id) references profile (id);
	  """)
  }

  //oracle
  changeSet(author: "marketplace", id: "2.3.1-1", context: "create, 2.3.1", dbms: "oracle") {
	  comment( "DDL statements for creating Marketplace 2.3.1 database structure" )
      preConditions (onFail:"MARK_RAN") {
          not {
              tableExists(tableName:"service_item")
          }
      }
      sql ( """
		create table U_DOMAIN (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, username varchar2(255 char) not null, created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table U_DOMAIN_preferences (preferences number(19,0), preferences_idx varchar2(255 char), preferences_elt varchar2(255 char) not null);
		create table U_VIEWS (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, isadminview number(1,0) not null, created_by_id number(19,0), name varchar2(255 char) not null, isdefault number(1,0) not null, edited_date timestamp, primary key (id));
		create table avatar (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, is_default number(1,0) not null, pic long raw, created_by_id number(19,0), content_type varchar2(255 char), edited_date timestamp, primary key (id));
		create table category (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, title varchar2(50 char) not null, description varchar2(250 char), created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table change_detail (id number(19,0) not null, version number(19,0) not null, new_value varchar2(4000 char), object_version number(19,0) not null, object_id number(19,0) not null, field_name varchar2(255 char) not null, old_value varchar2(4000 char), object_class_name varchar2(255 char) not null, primary key (id));
		create table change_log (id number(19,0) not null, version number(19,0) not null, object_version number(19,0) not null, changed_by_id number(19,0) not null, object_id number(19,0) not null, description varchar2(255 char) not null, object_class_name varchar2(255 char) not null, change_date timestamp not null, primary key (id));
		create table custom_field (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, custom_field_definition_id number(19,0) not null, created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table custom_field_definition (id number(19,0) not null, version number(19,0) not null, created_date timestamp, tooltip varchar2(50 char), created_by_id number(19,0), edited_date timestamp, edited_by_id number(19,0), label varchar2(50 char) not null, description varchar2(250 char), is_required number(1,0) not null, name varchar2(50 char) not null, style_type varchar2(255 char) not null, primary key (id));
		create table custom_field_definition_types (cf_definition_types_id number(19,0), types_id number(19,0), types_idx number(10,0));
		create table default_images (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, image_id number(19,0) not null, created_by_id number(19,0), defined_default_type varchar2(255 char) not null, edited_date timestamp, primary key (id));
		create table drop_down_cf (id number(19,0) not null, value_id number(19,0), primary key (id));
		create table drop_down_cfd (id number(19,0) not null, primary key (id));
		create table ext_profile (id number(19,0) not null, external_view_url varchar2(2083 char), system_uri varchar2(255 char), external_id varchar2(255 char), external_edit_url varchar2(2083 char), primary key (id), unique (system_uri, external_id));
		create table ext_service_item (id number(19,0) not null, external_view_url varchar2(2083 char), system_uri varchar2(255 char), external_id varchar2(255 char), external_edit_url varchar2(2083 char), primary key (id), unique (system_uri, external_id));
		create table field_value (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, custom_field_definition_id number(19,0) not null, is_enabled number(10,0) not null, display_text varchar2(255 char) not null, created_by_id number(19,0), edited_date timestamp, field_values_idx number(10,0), primary key (id));
		create table images (id number(19,0) not null, version number(19,0) not null, created_date timestamp, is_default number(1,0) not null, type varchar2(255 char) not null, created_by_id number(19,0), content_type varchar2(255 char), bytes long raw not null, edited_date timestamp, edited_by_id number(19,0), image_size double precision, primary key (id));
		create table item_comment (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, service_item_id number(19,0) not null, text varchar2(250 char) not null, created_by_id number(19,0), author_id number(19,0) not null, edited_date timestamp, primary key (id));
		create table modify_relationship_activity (id number(19,0) not null, primary key (id));
		create table owf_properties (id number(19,0) not null, version number(19,0) not null, visible_in_launch number(1,0) not null, edited_by_id number(19,0), created_date timestamp, singleton number(1,0) not null, created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table profile (id number(19,0) not null, version number(19,0) not null, created_date timestamp not null, created_by_id number(19,0), bio varchar2(1000 char), edited_date timestamp, edited_by_id number(19,0), username varchar2(250 char) not null unique, email varchar2(250 char), avatar_id number(19,0), display_name varchar2(250 char), primary key (id));
		create table rating (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, service_item_id number(19,0) not null, created_by_id number(19,0), author_id number(19,0) not null, rate float not null, edited_date timestamp, primary key (id));
		create table rejection_activity (id number(19,0) not null, rejection_listing_id number(19,0), primary key (id));
		create table rejection_justification (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, title varchar2(50 char) not null, description varchar2(250 char), created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table rejection_listing (id number(19,0) not null, version number(19,0) not null, justification_id number(19,0), edited_by_id number(19,0), created_date timestamp, service_item_id number(19,0) not null, description varchar2(2000 char), created_by_id number(19,0), author_id number(19,0) not null, edited_date timestamp, primary key (id));
		create table relationship (id number(19,0) not null, version number(19,0) not null, relationship_type varchar2(255 char) not null, owning_entity_id number(19,0) not null, primary key (id));
		create table relationship_activity_log (mod_rel_activity_id number(19,0) not null, service_item_snapshot_id number(19,0), items_idx number(10,0));
		create table relationship_service_item (relationship_related_items_id number(19,0), service_item_id number(19,0), related_items_idx number(10,0));
		create table service_item (id number(19,0) not null, version number(19,0) not null, created_date timestamp, owf_properties_id number(19,0), avg_rate float not null, approval_status varchar2(11 char) not null, title varchar2(50 char) not null, screenshot1url varchar2(2083 char), image_small_url varchar2(2083 char), image_large_url varchar2(2083 char), total_votes number(10,0) not null, launch_url varchar2(2083 char), uuid varchar2(255 char) not null, version_name varchar2(50 char) not null, release_date timestamp not null, organization varchar2(40 char), dependencies varchar2(1000 char), types_id number(19,0) not null, screenshot2url varchar2(2083 char), created_by_id number(19,0), requirements varchar2(1000 char), doc_url varchar2(2083 char), tech_poc varchar2(255 char) not null, edited_date timestamp, edited_by_id number(19,0), total_comments number(10,0) not null, is_hidden number(10,0) not null, description varchar2(4000 char) not null, state_id number(19,0) not null, install_url varchar2(2083 char), last_activity_id number(19,0), author_id number(19,0) not null, primary key (id));
		create table service_item_activity (id number(19,0) not null, version number(19,0) not null, created_date timestamp, action varchar2(255 char) not null, service_item_id number(19,0) not null, service_item_version number(19,0), created_by_id number(19,0), edited_date timestamp, edited_by_id number(19,0), activity_timestamp timestamp not null, author_id number(19,0) not null, service_item_activities_idx number(10,0), primary key (id));
		create table service_item_category (service_item_categories_id number(19,0) not null, category_id number(19,0), categories_idx number(10,0));
		create table service_item_custom_field (service_item_custom_fields_id number(19,0), custom_field_id number(19,0), custom_fields_idx number(10,0));
		create table service_item_snapshot (id number(19,0) not null, version number(19,0) not null, service_item_id number(19,0), title varchar2(255 char) not null, primary key (id));
		create table si_recommended_layouts (service_item_id number(19,0), recommended_layout varchar2(255 char));
		create table state (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, is_published number(1,0) not null, title varchar2(50 char) not null, description varchar2(250 char), created_by_id number(19,0), edited_date timestamp, primary key (id));
		create table text (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, value varchar2(250 char), created_by_id number(19,0), read_only number(1,0) not null, name varchar2(50 char) not null unique, edited_date timestamp, primary key (id));
		create table text_cf (id number(19,0) not null, value varchar2(255 char), primary key (id));
		create table text_cfd (id number(19,0) not null, primary key (id));
		create table types (id number(19,0) not null, version number(19,0) not null, created_date timestamp, title varchar2(50 char) not null, created_by_id number(19,0), role_access varchar2(9 char) not null, edited_date timestamp, edited_by_id number(19,0), has_launch_url number(1,0) not null, is_widget number(1,0) not null, description varchar2(250 char), image_id number(19,0), ozone_aware number(1,0) not null, has_icons number(1,0) not null, primary key (id));
		create table user_account (id number(19,0) not null, version number(19,0) not null, edited_by_id number(19,0), created_date timestamp, username varchar2(250 char) not null unique, created_by_id number(19,0), last_login timestamp, edited_date timestamp, primary key (id));
		alter table U_DOMAIN add constraint FK97BAABEE7666C6D2 foreign key (created_by_id) references profile;
		alter table U_DOMAIN add constraint FK97BAABEEE31CB353 foreign key (edited_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E47666C6D2 foreign key (created_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E4E31CB353 foreign key (edited_by_id) references profile;
		alter table avatar add constraint FKAC32C1597666C6D2 foreign key (created_by_id) references profile;
		alter table avatar add constraint FKAC32C159E31CB353 foreign key (edited_by_id) references profile;
		alter table category add constraint FK302BCFE7666C6D2 foreign key (created_by_id) references profile;
		alter table category add constraint FK302BCFEE31CB353 foreign key (edited_by_id) references profile;
		alter table change_log add constraint FK80F28E35B624A19E foreign key (changed_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC7666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field add constraint FK2ACD76ACE31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC6F62C9ED foreign key (custom_field_definition_id) references custom_field_definition;
		alter table custom_field_definition add constraint FK150F70C6E31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field_definition add constraint FK150F70C67666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field_definition_types add constraint FK1A84FFC06928D597 foreign key (types_id) references types;
		alter table default_images add constraint FK6F064E367666C6D2 foreign key (created_by_id) references profile;
		alter table default_images add constraint FK6F064E36E31CB353 foreign key (edited_by_id) references profile;
		alter table default_images add constraint FK6F064E36553AF61A foreign key (image_id) references images;
		alter table drop_down_cf add constraint FK13ADE7D0BC98CEE3 foreign key (value_id) references field_value;
		alter table field_value add constraint FK29F571EC7666C6D2 foreign key (created_by_id) references profile;
		alter table field_value add constraint FK29F571ECE31CB353 foreign key (edited_by_id) references profile;
		alter table field_value add constraint FK29F571ECF1F14D3C foreign key (custom_field_definition_id) references drop_down_cfd;
		alter table images add constraint FKB95A8278E31CB353 foreign key (edited_by_id) references profile;
		alter table images add constraint FKB95A82787666C6D2 foreign key (created_by_id) references profile;
		create index itm_cmnt_svc_item_id_idx on item_comment (service_item_id);
		create index itm_cmnt_author_id_idx on item_comment (author_id);
		alter table item_comment add constraint FKE6D04D337666C6D2 foreign key (created_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33E31CB353 foreign key (edited_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33C7E5C662 foreign key (service_item_id) references service_item;
		alter table item_comment add constraint FKE6D04D335A032135 foreign key (author_id) references profile;
		alter table owf_properties add constraint FKE88638947666C6D2 foreign key (created_by_id) references profile;
		alter table owf_properties add constraint FKE8863894E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A9E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A97666C6D2 foreign key (created_by_id) references profile;
		alter table profile add constraint FKED8E89A961C3343D foreign key (avatar_id) references avatar;
		create index rating_svc_item_id_idx on rating (service_item_id);
		alter table rating add constraint FKC815B19D7666C6D2 foreign key (created_by_id) references profile;
		alter table rating add constraint FKC815B19DE31CB353 foreign key (edited_by_id) references profile;
		alter table rating add constraint FKC815B19DC7E5C662 foreign key (service_item_id) references service_item;
		alter table rating add constraint FKC815B19D5A032135 foreign key (author_id) references profile;
		alter table rejection_activity add constraint FKF35C128582548A4A foreign key (rejection_listing_id) references rejection_listing;
		alter table rejection_justification add constraint FK12B0A53C7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_justification add constraint FK12B0A53CE31CB353 foreign key (edited_by_id) references profile;
		create index rej_lst_svc_item_id_idx on rejection_listing (service_item_id);
		alter table rejection_listing add constraint FK3F2BD44E7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EE31CB353 foreign key (edited_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EC7E5C662 foreign key (service_item_id) references service_item;
		alter table rejection_listing add constraint FK3F2BD44E5A032135 foreign key (author_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44E19CEB614 foreign key (justification_id) references rejection_justification;
		alter table relationship add constraint FKF06476389D70DD39 foreign key (owning_entity_id) references service_item;
		alter table relationship_activity_log add constraint FK594974BB25A20F9D foreign key (service_item_snapshot_id) references service_item_snapshot;
		alter table relationship_service_item add constraint FKDA02504C7E5C662 foreign key (service_item_id) references service_item;
		create index svc_item_author_id_idx on service_item (author_id);
		alter table service_item add constraint FK1571565D2746B676 foreign key (last_activity_id) references service_item_activity;
		alter table service_item add constraint FK1571565D904D6974 foreign key (owf_properties_id) references owf_properties;
		alter table service_item add constraint FK1571565DE31CB353 foreign key (edited_by_id) references profile;
		alter table service_item add constraint FK1571565D7666C6D2 foreign key (created_by_id) references profile;
		alter table service_item add constraint FK1571565D6928D597 foreign key (types_id) references types;
		alter table service_item add constraint FK1571565D5A032135 foreign key (author_id) references profile;
		alter table service_item add constraint FK1571565DDFEC3E97 foreign key (state_id) references state;
		create index svc_item_act_svc_item_id_idx on service_item_activity (service_item_id);
		alter table service_item_activity add constraint FK870EA6B1E31CB353 foreign key (edited_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B17666C6D2 foreign key (created_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B1C7E5C662 foreign key (service_item_id) references service_item;
		alter table service_item_activity add constraint FK870EA6B15A032135 foreign key (author_id) references profile;
		create index svc_item_cat_id_idx on service_item_category (service_item_categories_id);
		alter table service_item_category add constraint FKECC570A0DA41995D foreign key (category_id) references category;
		create index svc_item_cst_fld_id_idx on service_item_custom_field (service_item_custom_fields_id);
		alter table service_item_custom_field add constraint FK46E9894E7B56E054 foreign key (custom_field_id) references custom_field;
		alter table service_item_snapshot add constraint FKFABD8966C7E5C662 foreign key (service_item_id) references service_item;
		alter table si_recommended_layouts add constraint FK863C793CC7E5C662 foreign key (service_item_id) references service_item;
		alter table state add constraint FK68AC4917666C6D2 foreign key (created_by_id) references profile;
		alter table state add constraint FK68AC491E31CB353 foreign key (edited_by_id) references profile;
		alter table text add constraint FK36452D7666C6D2 foreign key (created_by_id) references profile;
		alter table text add constraint FK36452DE31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B5879E31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B58797666C6D2 foreign key (created_by_id) references profile;
		alter table types add constraint FK69B5879553AF61A foreign key (image_id) references images;
		alter table user_account add constraint FK14C321B97666C6D2 foreign key (created_by_id) references profile;
		alter table user_account add constraint FK14C321B9E31CB353 foreign key (edited_by_id) references profile;
		create sequence hibernate_sequence;
	  """)
  }

  //postgres
  changeSet(author: "marketplace", id: "2.3.1-1", context: "create, 2.3.1", dbms: "postgresql") {
	  comment( "DDL statements for creating Marketplace 2.3.1 database structure" )
      preConditions (onFail:"MARK_RAN") {
          not {
              tableExists(tableName:"service_item")
          }
      }
      sql ( """
		create table U_DOMAIN (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, username varchar(255) not null, created_by_id int8, edited_date timestamp, primary key (id));
		create table U_DOMAIN_preferences (preferences int8, preferences_idx varchar(255), preferences_elt varchar(255) not null);
		create table U_VIEWS (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, isadminview bool not null, created_by_id int8, name varchar(255) not null, isdefault bool not null, edited_date timestamp, primary key (id));
		create table avatar (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, is_default bool not null, pic bytea, created_by_id int8, content_type varchar(255), edited_date timestamp, primary key (id));
		create table category (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, title varchar(50) not null, description varchar(250), created_by_id int8, edited_date timestamp, primary key (id));
		create table change_detail (id int8 not null, version int8 not null, new_value varchar(4000), object_version int8 not null, object_id int8 not null, field_name varchar(255) not null, old_value varchar(4000), object_class_name varchar(255) not null, primary key (id));
		create table change_log (id int8 not null, version int8 not null, object_version int8 not null, changed_by_id int8 not null, object_id int8 not null, description varchar(255) not null, object_class_name varchar(255) not null, change_date timestamp not null, primary key (id));
		create table custom_field (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, custom_field_definition_id int8 not null, created_by_id int8, edited_date timestamp, primary key (id));
		create table custom_field_definition (id int8 not null, version int8 not null, created_date timestamp, tooltip varchar(50), created_by_id int8, edited_date timestamp, edited_by_id int8, label varchar(50) not null, description varchar(250), is_required bool not null, name varchar(50) not null, style_type varchar(255) not null, primary key (id));
		create table custom_field_definition_types (cf_definition_types_id int8, types_id int8, types_idx int4);
		create table default_images (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, image_id int8 not null, created_by_id int8, defined_default_type varchar(255) not null, edited_date timestamp, primary key (id));
		create table drop_down_cf (id int8 not null, value_id int8, primary key (id));
		create table drop_down_cfd (id int8 not null, primary key (id));
		create table ext_profile (id int8 not null, external_view_url varchar(2083), system_uri varchar(255), external_id varchar(255), external_edit_url varchar(2083), primary key (id), unique (system_uri, external_id));
		create table ext_service_item (id int8 not null, external_view_url varchar(2083), system_uri varchar(255), external_id varchar(255), external_edit_url varchar(2083), primary key (id), unique (system_uri, external_id));
		create table field_value (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, custom_field_definition_id int8 not null, is_enabled int4 not null, display_text varchar(255) not null, created_by_id int8, edited_date timestamp, field_values_idx int4, primary key (id));
		create table images (id int8 not null, version int8 not null, created_date timestamp, is_default bool not null, type varchar(255) not null, created_by_id int8, content_type varchar(255), bytes bytea not null, edited_date timestamp, edited_by_id int8, image_size float8, primary key (id));
		create table item_comment (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, service_item_id int8 not null, text varchar(250) not null, created_by_id int8, author_id int8 not null, edited_date timestamp, primary key (id));
		create table modify_relationship_activity (id int8 not null, primary key (id));
		create table owf_properties (id int8 not null, version int8 not null, visible_in_launch bool not null, edited_by_id int8, created_date timestamp, singleton bool not null, created_by_id int8, edited_date timestamp, primary key (id));
		create table profile (id int8 not null, version int8 not null, created_date timestamp not null, created_by_id int8, bio varchar(1000), edited_date timestamp, edited_by_id int8, username varchar(250) not null unique, email varchar(250), avatar_id int8, display_name varchar(250), primary key (id));
		create table rating (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, service_item_id int8 not null, created_by_id int8, author_id int8 not null, rate float4 not null, edited_date timestamp, primary key (id));
		create table rejection_activity (id int8 not null, rejection_listing_id int8, primary key (id));
		create table rejection_justification (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, title varchar(50) not null, description varchar(250), created_by_id int8, edited_date timestamp, primary key (id));
		create table rejection_listing (id int8 not null, version int8 not null, justification_id int8, edited_by_id int8, created_date timestamp, service_item_id int8 not null, description varchar(2000), created_by_id int8, author_id int8 not null, edited_date timestamp, primary key (id));
		create table relationship (id int8 not null, version int8 not null, relationship_type varchar(255) not null, owning_entity_id int8 not null, primary key (id));
		create table relationship_activity_log (mod_rel_activity_id int8 not null, service_item_snapshot_id int8, items_idx int4);
		create table relationship_service_item (relationship_related_items_id int8, service_item_id int8, related_items_idx int4);
		create table service_item (id int8 not null, version int8 not null, created_date timestamp, owf_properties_id int8, avg_rate float4 not null, approval_status varchar(11) not null, title varchar(50) not null, screenshot1url varchar(2083), image_small_url varchar(2083), image_large_url varchar(2083), total_votes int4 not null, launch_url varchar(2083), uuid varchar(255) not null, version_name varchar(50) not null, release_date timestamp not null, organization varchar(40), dependencies varchar(1000), types_id int8 not null, screenshot2url varchar(2083), created_by_id int8, requirements varchar(1000), doc_url varchar(2083), tech_poc varchar(255) not null, edited_date timestamp, edited_by_id int8, total_comments int4 not null, is_hidden int4 not null, description varchar(4000) not null, state_id int8 not null, install_url varchar(2083), last_activity_id int8, author_id int8 not null, primary key (id));
		create table service_item_activity (id int8 not null, version int8 not null, created_date timestamp, action varchar(255) not null, service_item_id int8 not null, service_item_version int8, created_by_id int8, edited_date timestamp, edited_by_id int8, activity_timestamp timestamp not null, author_id int8 not null, service_item_activities_idx int4, primary key (id));
		create table service_item_category (service_item_categories_id int8 not null, category_id int8, categories_idx int4);
		create table service_item_custom_field (service_item_custom_fields_id int8, custom_field_id int8, custom_fields_idx int4);
		create table service_item_snapshot (id int8 not null, version int8 not null, service_item_id int8, title varchar(255) not null, primary key (id));
		create table si_recommended_layouts (service_item_id int8, recommended_layout varchar(255));
		create table state (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, is_published bool not null, title varchar(50) not null, description varchar(250), created_by_id int8, edited_date timestamp, primary key (id));
		create table text (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, value varchar(250), created_by_id int8, read_only bool not null, name varchar(50) not null unique, edited_date timestamp, primary key (id));
		create table text_cf (id int8 not null, value varchar(255), primary key (id));
		create table text_cfd (id int8 not null, primary key (id));
		create table types (id int8 not null, version int8 not null, created_date timestamp, title varchar(50) not null, created_by_id int8, role_access varchar(9) not null, edited_date timestamp, edited_by_id int8, has_launch_url bool not null, is_widget bool not null, description varchar(250), image_id int8, ozone_aware bool not null, has_icons bool not null, primary key (id));
		create table user_account (id int8 not null, version int8 not null, edited_by_id int8, created_date timestamp, username varchar(250) not null unique, created_by_id int8, last_login timestamp, edited_date timestamp, primary key (id));
		alter table U_DOMAIN add constraint FK97BAABEE7666C6D2 foreign key (created_by_id) references profile;
		alter table U_DOMAIN add constraint FK97BAABEEE31CB353 foreign key (edited_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E47666C6D2 foreign key (created_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E4E31CB353 foreign key (edited_by_id) references profile;
		alter table avatar add constraint FKAC32C1597666C6D2 foreign key (created_by_id) references profile;
		alter table avatar add constraint FKAC32C159E31CB353 foreign key (edited_by_id) references profile;
		alter table category add constraint FK302BCFE7666C6D2 foreign key (created_by_id) references profile;
		alter table category add constraint FK302BCFEE31CB353 foreign key (edited_by_id) references profile;
		alter table change_log add constraint FK80F28E35B624A19E foreign key (changed_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC7666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field add constraint FK2ACD76ACE31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC6F62C9ED foreign key (custom_field_definition_id) references custom_field_definition;
		alter table custom_field_definition add constraint FK150F70C6E31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field_definition add constraint FK150F70C67666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field_definition_types add constraint FK1A84FFC06928D597 foreign key (types_id) references types;
		alter table default_images add constraint FK6F064E367666C6D2 foreign key (created_by_id) references profile;
		alter table default_images add constraint FK6F064E36E31CB353 foreign key (edited_by_id) references profile;
		alter table default_images add constraint FK6F064E36553AF61A foreign key (image_id) references images;
		alter table drop_down_cf add constraint FK13ADE7D0BC98CEE3 foreign key (value_id) references field_value;
		alter table field_value add constraint FK29F571EC7666C6D2 foreign key (created_by_id) references profile;
		alter table field_value add constraint FK29F571ECE31CB353 foreign key (edited_by_id) references profile;
		alter table field_value add constraint FK29F571ECF1F14D3C foreign key (custom_field_definition_id) references drop_down_cfd;
		alter table images add constraint FKB95A8278E31CB353 foreign key (edited_by_id) references profile;
		alter table images add constraint FKB95A82787666C6D2 foreign key (created_by_id) references profile;
		create index itm_cmnt_svc_item_id_idx on item_comment (service_item_id);
		create index itm_cmnt_author_id_idx on item_comment (author_id);
		alter table item_comment add constraint FKE6D04D337666C6D2 foreign key (created_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33E31CB353 foreign key (edited_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33C7E5C662 foreign key (service_item_id) references service_item;
		alter table item_comment add constraint FKE6D04D335A032135 foreign key (author_id) references profile;
		alter table owf_properties add constraint FKE88638947666C6D2 foreign key (created_by_id) references profile;
		alter table owf_properties add constraint FKE8863894E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A9E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A97666C6D2 foreign key (created_by_id) references profile;
		alter table profile add constraint FKED8E89A961C3343D foreign key (avatar_id) references avatar;
		create index rating_svc_item_id_idx on rating (service_item_id);
		alter table rating add constraint FKC815B19D7666C6D2 foreign key (created_by_id) references profile;
		alter table rating add constraint FKC815B19DE31CB353 foreign key (edited_by_id) references profile;
		alter table rating add constraint FKC815B19DC7E5C662 foreign key (service_item_id) references service_item;
		alter table rating add constraint FKC815B19D5A032135 foreign key (author_id) references profile;
		alter table rejection_activity add constraint FKF35C128582548A4A foreign key (rejection_listing_id) references rejection_listing;
		alter table rejection_justification add constraint FK12B0A53C7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_justification add constraint FK12B0A53CE31CB353 foreign key (edited_by_id) references profile;
		create index rej_lst_svc_item_id_idx on rejection_listing (service_item_id);
		alter table rejection_listing add constraint FK3F2BD44E7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EE31CB353 foreign key (edited_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EC7E5C662 foreign key (service_item_id) references service_item;
		alter table rejection_listing add constraint FK3F2BD44E5A032135 foreign key (author_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44E19CEB614 foreign key (justification_id) references rejection_justification;
		alter table relationship add constraint FKF06476389D70DD39 foreign key (owning_entity_id) references service_item;
		alter table relationship_activity_log add constraint FK594974BB25A20F9D foreign key (service_item_snapshot_id) references service_item_snapshot;
		alter table relationship_service_item add constraint FKDA02504C7E5C662 foreign key (service_item_id) references service_item;
		create index svc_item_author_id_idx on service_item (author_id);
		alter table service_item add constraint FK1571565D2746B676 foreign key (last_activity_id) references service_item_activity;
		alter table service_item add constraint FK1571565D904D6974 foreign key (owf_properties_id) references owf_properties;
		alter table service_item add constraint FK1571565DE31CB353 foreign key (edited_by_id) references profile;
		alter table service_item add constraint FK1571565D7666C6D2 foreign key (created_by_id) references profile;
		alter table service_item add constraint FK1571565D6928D597 foreign key (types_id) references types;
		alter table service_item add constraint FK1571565D5A032135 foreign key (author_id) references profile;
		alter table service_item add constraint FK1571565DDFEC3E97 foreign key (state_id) references state;
		create index svc_item_act_svc_item_id_idx on service_item_activity (service_item_id);
		alter table service_item_activity add constraint FK870EA6B1E31CB353 foreign key (edited_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B17666C6D2 foreign key (created_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B1C7E5C662 foreign key (service_item_id) references service_item;
		alter table service_item_activity add constraint FK870EA6B15A032135 foreign key (author_id) references profile;
		create index svc_item_cat_id_idx on service_item_category (service_item_categories_id);
		alter table service_item_category add constraint FKECC570A0DA41995D foreign key (category_id) references category;
		create index svc_item_cst_fld_id_idx on service_item_custom_field (service_item_custom_fields_id);
		alter table service_item_custom_field add constraint FK46E9894E7B56E054 foreign key (custom_field_id) references custom_field;
		alter table service_item_snapshot add constraint FKFABD8966C7E5C662 foreign key (service_item_id) references service_item;
		alter table si_recommended_layouts add constraint FK863C793CC7E5C662 foreign key (service_item_id) references service_item;
		alter table state add constraint FK68AC4917666C6D2 foreign key (created_by_id) references profile;
		alter table state add constraint FK68AC491E31CB353 foreign key (edited_by_id) references profile;
		alter table text add constraint FK36452D7666C6D2 foreign key (created_by_id) references profile;
		alter table text add constraint FK36452DE31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B5879E31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B58797666C6D2 foreign key (created_by_id) references profile;
		alter table types add constraint FK69B5879553AF61A foreign key (image_id) references images;
		alter table user_account add constraint FK14C321B97666C6D2 foreign key (created_by_id) references profile;
		alter table user_account add constraint FK14C321B9E31CB353 foreign key (edited_by_id) references profile;
		create sequence hibernate_sequence;
	  """)
  }

  //sqlserver
  changeSet(author: "marketplace", id: "2.3.1-1", context: "create, 2.3.1", dbms: "mssql") {
	  comment( "DDL statements for creating Marketplace 2.3.1 database structure" )
      preConditions (onFail:"MARK_RAN") {
          not {
              tableExists(tableName:"service_item")
          }
      }
      sql ( """
		create table U_DOMAIN (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, username nvarchar(255) not null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table U_DOMAIN_preferences (preferences numeric(19,0) null, preferences_idx nvarchar(255) null, preferences_elt nvarchar(255) not null);
		create table U_VIEWS (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, isadminview tinyint not null, created_by_id numeric(19,0) null, name nvarchar(255) not null, isdefault tinyint not null, edited_date datetime null, primary key (id));
		create table avatar (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, is_default tinyint not null, pic image null, created_by_id numeric(19,0) null, content_type nvarchar(255) null, edited_date datetime null, primary key (id));
		create table category (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, title nvarchar(50) not null, description nvarchar(250) null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table change_detail (id numeric(19,0) identity not null, version numeric(19,0) not null, new_value nvarchar(4000) null, object_version numeric(19,0) not null, object_id numeric(19,0) not null, field_name nvarchar(255) not null, old_value nvarchar(4000) null, object_class_name nvarchar(255) not null, primary key (id));
		create table change_log (id numeric(19,0) identity not null, version numeric(19,0) not null, object_version numeric(19,0) not null, changed_by_id numeric(19,0) not null, object_id numeric(19,0) not null, description nvarchar(255) not null, object_class_name nvarchar(255) not null, change_date datetime not null, primary key (id));
		create table custom_field (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, custom_field_definition_id numeric(19,0) not null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table custom_field_definition (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime null, tooltip nvarchar(50) null, created_by_id numeric(19,0) null, edited_date datetime null, edited_by_id numeric(19,0) null, label nvarchar(50) not null, description nvarchar(250) null, is_required tinyint not null, name nvarchar(50) not null, style_type nvarchar(255) not null, primary key (id));
		create table custom_field_definition_types (cf_definition_types_id numeric(19,0) null, types_id numeric(19,0) null, types_idx int null);
		create table default_images (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, image_id numeric(19,0) not null, created_by_id numeric(19,0) null, defined_default_type nvarchar(255) not null, edited_date datetime null, primary key (id));
		create table drop_down_cf (id numeric(19,0) not null, value_id numeric(19,0) null, primary key (id));
		create table drop_down_cfd (id numeric(19,0) not null, primary key (id));
		create table ext_profile (id numeric(19,0) not null, external_view_url nvarchar(2083) null, system_uri nvarchar(255) null, external_id nvarchar(255) null, external_edit_url nvarchar(2083) null, primary key (id), unique (system_uri, external_id));
		create table ext_service_item (id numeric(19,0) not null, external_view_url nvarchar(2083) null, system_uri nvarchar(255) null, external_id nvarchar(255) null, external_edit_url nvarchar(2083) null, primary key (id), unique (system_uri, external_id));
		create table field_value (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, custom_field_definition_id numeric(19,0) not null, is_enabled int not null, display_text nvarchar(255) not null, created_by_id numeric(19,0) null, edited_date datetime null, field_values_idx int null, primary key (id));
		create table images (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime null, is_default tinyint not null, type nvarchar(255) not null, created_by_id numeric(19,0) null, content_type nvarchar(255) null, bytes image not null, edited_date datetime null, edited_by_id numeric(19,0) null, image_size double precision null, primary key (id));
		create table item_comment (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, service_item_id numeric(19,0) not null, text nvarchar(250) not null, created_by_id numeric(19,0) null, author_id numeric(19,0) not null, edited_date datetime null, primary key (id));
		create table modify_relationship_activity (id numeric(19,0) not null, primary key (id));
		create table owf_properties (id numeric(19,0) identity not null, version numeric(19,0) not null, visible_in_launch tinyint not null, edited_by_id numeric(19,0) null, created_date datetime null, singleton tinyint not null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table profile (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime not null, created_by_id numeric(19,0) null, bio nvarchar(1000) null, edited_date datetime null, edited_by_id numeric(19,0) null, username nvarchar(250) not null unique, email nvarchar(250) null, avatar_id numeric(19,0) null, display_name nvarchar(250) null, primary key (id));
		create table rating (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, service_item_id numeric(19,0) not null, created_by_id numeric(19,0) null, author_id numeric(19,0) not null, rate float not null, edited_date datetime null, primary key (id));
		create table rejection_activity (id numeric(19,0) not null, rejection_listing_id numeric(19,0) null, primary key (id));
		create table rejection_justification (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, title nvarchar(50) not null, description nvarchar(250) null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table rejection_listing (id numeric(19,0) identity not null, version numeric(19,0) not null, justification_id numeric(19,0) null, edited_by_id numeric(19,0) null, created_date datetime null, service_item_id numeric(19,0) not null, description nvarchar(2000) null, created_by_id numeric(19,0) null, author_id numeric(19,0) not null, edited_date datetime null, primary key (id));
		create table relationship (id numeric(19,0) identity not null, version numeric(19,0) not null, relationship_type nvarchar(255) not null, owning_entity_id numeric(19,0) not null, primary key (id));
		create table relationship_activity_log (mod_rel_activity_id numeric(19,0) not null, service_item_snapshot_id numeric(19,0) null, items_idx int null);
		create table relationship_service_item (relationship_related_items_id numeric(19,0) null, service_item_id numeric(19,0) null, related_items_idx int null);
		create table service_item (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime null, owf_properties_id numeric(19,0) null, avg_rate float not null, approval_status nvarchar(11) not null, title nvarchar(50) not null, screenshot1url nvarchar(2083) null, image_small_url nvarchar(2083) null, image_large_url nvarchar(2083) null, total_votes int not null, launch_url nvarchar(2083) null, uuid nvarchar(255) not null, version_name nvarchar(50) not null, release_date datetime not null, organization nvarchar(40) null, dependencies nvarchar(1000) null, types_id numeric(19,0) not null, screenshot2url nvarchar(2083) null, created_by_id numeric(19,0) null, requirements nvarchar(1000) null, doc_url nvarchar(2083) null, tech_poc nvarchar(255) not null, edited_date datetime null, edited_by_id numeric(19,0) null, total_comments int not null, is_hidden int not null, description nvarchar(4000) not null, state_id numeric(19,0) not null, install_url nvarchar(2083) null, last_activity_id numeric(19,0) null, author_id numeric(19,0) not null, primary key (id));
		create table service_item_activity (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime null, action nvarchar(255) not null, service_item_id numeric(19,0) not null, service_item_version numeric(19,0) null, created_by_id numeric(19,0) null, edited_date datetime null, edited_by_id numeric(19,0) null, activity_timestamp datetime not null, author_id numeric(19,0) not null, service_item_activities_idx int null, primary key (id));
		create table service_item_category (service_item_categories_id numeric(19,0) not null, category_id numeric(19,0) null, categories_idx int null);
		create table service_item_custom_field (service_item_custom_fields_id numeric(19,0) null, custom_field_id numeric(19,0) null, custom_fields_idx int null);
		create table service_item_snapshot (id numeric(19,0) identity not null, version numeric(19,0) not null, service_item_id numeric(19,0) null, title nvarchar(255) not null, primary key (id));
		create table si_recommended_layouts (service_item_id numeric(19,0) null, recommended_layout nvarchar(255) null);
		create table state (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, is_published tinyint not null, title nvarchar(50) not null, description nvarchar(250) null, created_by_id numeric(19,0) null, edited_date datetime null, primary key (id));
		create table text (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, value nvarchar(250) null, created_by_id numeric(19,0) null, read_only tinyint not null, name nvarchar(50) not null unique, edited_date datetime null, primary key (id));
		create table text_cf (id numeric(19,0) not null, value nvarchar(255) null, primary key (id));
		create table text_cfd (id numeric(19,0) not null, primary key (id));
		create table types (id numeric(19,0) identity not null, version numeric(19,0) not null, created_date datetime null, title nvarchar(50) not null, created_by_id numeric(19,0) null, role_access nvarchar(9) not null, edited_date datetime null, edited_by_id numeric(19,0) null, has_launch_url tinyint not null, is_widget tinyint not null, description nvarchar(250) null, image_id numeric(19,0) null, ozone_aware tinyint not null, has_icons tinyint not null, primary key (id));
		create table user_account (id numeric(19,0) identity not null, version numeric(19,0) not null, edited_by_id numeric(19,0) null, created_date datetime null, username nvarchar(250) not null unique, created_by_id numeric(19,0) null, last_login datetime null, edited_date datetime null, primary key (id));
		alter table U_DOMAIN add constraint FK97BAABEE7666C6D2 foreign key (created_by_id) references profile;
		alter table U_DOMAIN add constraint FK97BAABEEE31CB353 foreign key (edited_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E47666C6D2 foreign key (created_by_id) references profile;
		alter table U_VIEWS add constraint FK376C31E4E31CB353 foreign key (edited_by_id) references profile;
		alter table avatar add constraint FKAC32C1597666C6D2 foreign key (created_by_id) references profile;
		alter table avatar add constraint FKAC32C159E31CB353 foreign key (edited_by_id) references profile;
		alter table category add constraint FK302BCFE7666C6D2 foreign key (created_by_id) references profile;
		alter table category add constraint FK302BCFEE31CB353 foreign key (edited_by_id) references profile;
		alter table change_log add constraint FK80F28E35B624A19E foreign key (changed_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC7666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field add constraint FK2ACD76ACE31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field add constraint FK2ACD76AC6F62C9ED foreign key (custom_field_definition_id) references custom_field_definition;
		alter table custom_field_definition add constraint FK150F70C6E31CB353 foreign key (edited_by_id) references profile;
		alter table custom_field_definition add constraint FK150F70C67666C6D2 foreign key (created_by_id) references profile;
		alter table custom_field_definition_types add constraint FK1A84FFC06928D597 foreign key (types_id) references types;
		alter table default_images add constraint FK6F064E367666C6D2 foreign key (created_by_id) references profile;
		alter table default_images add constraint FK6F064E36E31CB353 foreign key (edited_by_id) references profile;
		alter table default_images add constraint FK6F064E36553AF61A foreign key (image_id) references images;
		alter table drop_down_cf add constraint FK13ADE7D0BC98CEE3 foreign key (value_id) references field_value;
		alter table field_value add constraint FK29F571EC7666C6D2 foreign key (created_by_id) references profile;
		alter table field_value add constraint FK29F571ECE31CB353 foreign key (edited_by_id) references profile;
		alter table field_value add constraint FK29F571ECF1F14D3C foreign key (custom_field_definition_id) references drop_down_cfd;
		alter table images add constraint FKB95A8278E31CB353 foreign key (edited_by_id) references profile;
		alter table images add constraint FKB95A82787666C6D2 foreign key (created_by_id) references profile;
		create index itm_cmnt_svc_item_id_idx on item_comment (service_item_id);
		create index itm_cmnt_author_id_idx on item_comment (author_id);
		alter table item_comment add constraint FKE6D04D337666C6D2 foreign key (created_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33E31CB353 foreign key (edited_by_id) references profile;
		alter table item_comment add constraint FKE6D04D33C7E5C662 foreign key (service_item_id) references service_item;
		alter table item_comment add constraint FKE6D04D335A032135 foreign key (author_id) references profile;
		alter table owf_properties add constraint FKE88638947666C6D2 foreign key (created_by_id) references profile;
		alter table owf_properties add constraint FKE8863894E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A9E31CB353 foreign key (edited_by_id) references profile;
		alter table profile add constraint FKED8E89A97666C6D2 foreign key (created_by_id) references profile;
		alter table profile add constraint FKED8E89A961C3343D foreign key (avatar_id) references avatar;
		create index rating_svc_item_id_idx on rating (service_item_id);
		alter table rating add constraint FKC815B19D7666C6D2 foreign key (created_by_id) references profile;
		alter table rating add constraint FKC815B19DE31CB353 foreign key (edited_by_id) references profile;
		alter table rating add constraint FKC815B19DC7E5C662 foreign key (service_item_id) references service_item;
		alter table rating add constraint FKC815B19D5A032135 foreign key (author_id) references profile;
		alter table rejection_activity add constraint FKF35C128582548A4A foreign key (rejection_listing_id) references rejection_listing;
		alter table rejection_justification add constraint FK12B0A53C7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_justification add constraint FK12B0A53CE31CB353 foreign key (edited_by_id) references profile;
		create index rej_lst_svc_item_id_idx on rejection_listing (service_item_id);
		alter table rejection_listing add constraint FK3F2BD44E7666C6D2 foreign key (created_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EE31CB353 foreign key (edited_by_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44EC7E5C662 foreign key (service_item_id) references service_item;
		alter table rejection_listing add constraint FK3F2BD44E5A032135 foreign key (author_id) references profile;
		alter table rejection_listing add constraint FK3F2BD44E19CEB614 foreign key (justification_id) references rejection_justification;
		alter table relationship add constraint FKF06476389D70DD39 foreign key (owning_entity_id) references service_item;
		alter table relationship_activity_log add constraint FK594974BB25A20F9D foreign key (service_item_snapshot_id) references service_item_snapshot;
		alter table relationship_service_item add constraint FKDA02504C7E5C662 foreign key (service_item_id) references service_item;
		create index svc_item_author_id_idx on service_item (author_id);
		alter table service_item add constraint FK1571565D2746B676 foreign key (last_activity_id) references service_item_activity;
		alter table service_item add constraint FK1571565D904D6974 foreign key (owf_properties_id) references owf_properties;
		alter table service_item add constraint FK1571565DE31CB353 foreign key (edited_by_id) references profile;
		alter table service_item add constraint FK1571565D7666C6D2 foreign key (created_by_id) references profile;
		alter table service_item add constraint FK1571565D6928D597 foreign key (types_id) references types;
		alter table service_item add constraint FK1571565D5A032135 foreign key (author_id) references profile;
		alter table service_item add constraint FK1571565DDFEC3E97 foreign key (state_id) references state;
		create index svc_item_act_svc_item_id_idx on service_item_activity (service_item_id);
		alter table service_item_activity add constraint FK870EA6B1E31CB353 foreign key (edited_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B17666C6D2 foreign key (created_by_id) references profile;
		alter table service_item_activity add constraint FK870EA6B1C7E5C662 foreign key (service_item_id) references service_item;
		alter table service_item_activity add constraint FK870EA6B15A032135 foreign key (author_id) references profile;
		create index svc_item_cat_id_idx on service_item_category (service_item_categories_id);
		alter table service_item_category add constraint FKECC570A0DA41995D foreign key (category_id) references category;
		create index svc_item_cst_fld_id_idx on service_item_custom_field (service_item_custom_fields_id);
		alter table service_item_custom_field add constraint FK46E9894E7B56E054 foreign key (custom_field_id) references custom_field;
		alter table service_item_snapshot add constraint FKFABD8966C7E5C662 foreign key (service_item_id) references service_item;
		alter table si_recommended_layouts add constraint FK863C793CC7E5C662 foreign key (service_item_id) references service_item;
		alter table state add constraint FK68AC4917666C6D2 foreign key (created_by_id) references profile;
		alter table state add constraint FK68AC491E31CB353 foreign key (edited_by_id) references profile;
		alter table text add constraint FK36452D7666C6D2 foreign key (created_by_id) references profile;
		alter table text add constraint FK36452DE31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B5879E31CB353 foreign key (edited_by_id) references profile;
		alter table types add constraint FK69B58797666C6D2 foreign key (created_by_id) references profile;
		alter table types add constraint FK69B5879553AF61A foreign key (image_id) references images;
		alter table user_account add constraint FK14C321B97666C6D2 foreign key (created_by_id) references profile;
		alter table user_account add constraint FK14C321B9E31CB353 foreign key (edited_by_id) references profile;
	  """)
  }
}
